services:
  - type: web
    name: ss-bank
    env: node
    buildCommand: |
      npm install
      cd client
      npm install
      npm run build
      cd ..
      esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
      mkdir -p dist/client
      cp -r client/dist/* dist/client/
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SECURE_SITE
        value: "true"
      - key: EDUCATIONAL_DEMO
        value: "true" 