services:
  - type: web
    name: online-bank
    env: node
    buildCommand: |
      npm install
      cd client && npm install && npm run build
      mkdir -p ../dist/client
      cp -r dist/* ../dist/client/
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production 