services:
  - type: web
    name: ss-bank
    env: node
    buildCommand: npm run build
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SECURE_SITE
        value: "true"
      - key: EDUCATIONAL_DEMO
        value: "true" 