services:
  - type: web
    name: securebank
    env: node
    buildCommand: |
      npm install
      cd client
      npm install
      npm run build
      cd ..
      esbuild server/index.ts server/server-wrapper.ts server/optimize.ts server/performance.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
      mkdir -p dist/client
      cp -r client/dist/* dist/client/
    startCommand: NODE_ENV=production node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: SECURE_SITE
        value: "true"
      - key: EDUCATIONAL_DEMO
        value: "true"
      - key: ENABLE_CACHE
        value: "true"
      - key: COMPRESSION_LEVEL
        value: "6"
      - key: NODE_ENV
        value: "production" 