services:
  - type: web
    name: s-bank
    env: node
    buildCommand: |
      npm install
      cd client && npm install && npm run build
      cd ..
      mkdir -p dist/client
      cp -r client/dist/* dist/client/
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SECURE_SITE
        value: "true"
      - key: EDUCATIONAL_DEMO
        value: "true" 